
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.3 EDK_P.40xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xqspips.h"

/*
* The configuration table for devices
*/

XQspiPs_Config XQspiPs_ConfigTable[] =
{
	{
		XPAR_PS7_QSPI_0_DEVICE_ID,
		XPAR_PS7_QSPI_0_BASEADDR,
		XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ
	}
};


