TARGET := blackscholes
LDFLAGS := -lm
# RUNARGS := 1 in_64K.txt output.txt  # simlarge
# RUNARGS := 1 in_10M.txt output.txt  # native
RUNARGS := 1 in_1M.txt output.txt  # in between
CLEANMETOO := output.txt

APP_MK := ../app.mk
include $(APP_MK)
