TARGET := canneal
RUNARGS := 1 15000 2000 2500000.nets 6000  # native
# RUNARGS := 1 15000 2000 400000.nets 128  # simlarge
# RUNARGS := 1 100 300 100.nets 2  # simdev

APP_MK := ../app.mk
include $(APP_MK)
