/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.17/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_nosubdatabases1();
extern bool test_document1();
extern bool test_document2();
