/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.17/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_queryterms1();
extern bool test_matchnothing1();
extern bool test_nearsubqueries1();
extern bool test_xor3();
