/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.17/xapian/xapian-core/tests/collate-test - do not modify directly! */
extern bool test_closedb1();
extern bool test_closedb2();
extern bool test_closedb3();
extern bool test_closedb4();
extern bool test_closedb5();
extern bool test_closedb6();
extern bool test_closedb7();
extern bool test_closedb8();
extern bool test_closedb9();
extern bool test_closedb10();
