
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.3 EDK_P.40xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartps.h"

/*
* The configuration table for devices
*/

XUartPs_Config XUartPs_ConfigTable[] =
{
	{
		XPAR_PS7_UART_1_DEVICE_ID,
		XPAR_PS7_UART_1_BASEADDR,
		XPAR_PS7_UART_1_UART_CLK_FREQ_HZ,
		XPAR_PS7_UART_1_HAS_MODEM
	}
};


