/* Warning: This file is generated by /data/home/olly/tmp/xapian-svn-snapshot/tags/1.2.17/xapian/xapian-core/tests/collate-test - do not modify directly! */
#include "perftest/perftest_matchdecider.h"
#include "perftest/perftest_randomidx.h"
