TARGET := msp430-strawman
ARCH := msp430
CLANGARGS := -O2 -Werror -triple msp430-elf
CFLAGS := -D__MSP430__
CLANGARGS := -O2 -Werror
LINKER := msp430-gcc
LDFLAGS := -mmcu=msp430f2618

include ../app.mk
