
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.3 EDK_P.40xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xwdtps.h"

/*
* The configuration table for devices
*/

XWdtPs_Config XWdtPs_ConfigTable[] =
{
	{
		XPAR_PS7_WDT_0_DEVICE_ID,
		XPAR_PS7_WDT_0_BASEADDR
	}
};


